server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema
    username: newuser
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      exclude: static/**,public/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema
    username: root
    password: 04412345
